/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include <stdio.h>
#include "GUI_App.h"
#include "audioInputTools.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0  (GUI_ID_USER + 0x00)
#define ID_TEXT_0  (GUI_ID_USER + 0x01)
#define ID_TEXT_1  (GUI_ID_USER + 0x02)
#define ID_TEXT_2  (GUI_ID_USER + 0x03)
#define ID_BUTTON_0  (GUI_ID_USER + 0x04)
#define ID_BUTTON_1  (GUI_ID_USER + 0x05)
#define ID_BUTTON_2  (GUI_ID_USER + 0x06)
#define ID_PROGBAR_0  (GUI_ID_USER + 0x07)
#define ID_PROGBAR_1  (GUI_ID_USER + 0x08)

// USER START (Optionally insert additional defines)

// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
WM_HWIN hAudioRecordWin =0;
WM_HWIN hAudioRecordTextA = 0;
WM_HWIN hAudioRecordTextB = 0;
WM_HWIN hAudioRecordButtonA = 0;
WM_HWIN hAudioRecordButtonB = 0;
PROGBAR_Handle hAudioRecordBarA = 0;
PROGBAR_Handle hAudioRecordBarB = 0;
int enterAudioRecordPage = 0;
int isRecording = 0;
int isReplaying = 0;
int countFrames = 0;
int countReplayFrames = 0;
extern TIM_HandleTypeDef htim12;
// USER END

/*********************************************************************
*
*       _aWaveDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aAudioRecordDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 9, 9, 120, 33, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "0.0", ID_TEXT_1, 434, 128, 24, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "0.0", ID_TEXT_2, 435, 61, 32, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Back", ID_BUTTON_0, 396, 211, 57, 44, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Record", ID_BUTTON_1, 23, 55, 70, 29, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Play", ID_BUTTON_2, 23, 121, 70, 29, 0, 0x0, 0 },
  { PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_0, 113, 55, 312, 29, 0, 0x0, 0 },
  { PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_1, 112, 121, 312, 29, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbWaveDialog
*/
static void _cbAudioRecordDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetText(hItem, "Audio Record");
    TEXT_SetFont(hItem, GUI_FONT_20B_1);
    //
    // Initialization of '0.0'
    //
    hAudioRecordTextB = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hAudioRecordTextB, GUI_FONT_16B_1);
    TEXT_SetTextColor(hAudioRecordTextB, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of '0.0'
    //
    hAudioRecordTextA = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hAudioRecordTextA, GUI_FONT_16B_1);
    TEXT_SetTextColor(hAudioRecordTextA, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Back'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'Record'
    //
    hAudioRecordButtonA = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hAudioRecordButtonA, GUI_FONT_16_1);
    //
    // Initialization of 'Play'
    //
    hAudioRecordButtonB = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hAudioRecordButtonB, GUI_FONT_16_1);
    WM_DisableWindow(hAudioRecordButtonB);
    // USER START (Optionally insert additional code for further widget initialization)
    hAudioRecordBarA = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
    hAudioRecordBarB = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_1);
    
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Back'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
         enterAudioRecordPage = 0;
         AudioInputStop();
         isRecording = 0;
         countFrames = 0;
         isReplaying = 0;
         countReplayFrames = 0;
         __HAL_TIM_SET_COMPARE(&htim12,TIM_CHANNEL_1,0); 
         WM_EnableWindow(hAudioRecordButtonA);
         WM_DisableWindow(hAudioRecordButtonB);
         TEXT_SetText(hAudioRecordTextA,"0.0");
         PROGBAR_SetValue(hAudioRecordBarA,0);
         TEXT_SetText(hAudioRecordTextB,"0.0");
         PROGBAR_SetValue(hAudioRecordBarB,0);
         WM_HideWindow(hAudioRecordWin);
         WM_DeleteWindow(hAudioRecordWin);
         hAudioRecordWin = 0;
         if (!hWin) hWin = CreateWindow();
         WM_ShowWindow(hWin);
         
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Record'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        WM_DisableWindow(hAudioRecordButtonB);
        TEXT_SetText(hAudioRecordTextB,"0.0");
        PROGBAR_SetValue(hAudioRecordBarB,0);
        isRecording = 1;
        countFrames = 0;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Play'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        isReplaying = 1;
        countReplayFrames = 0;
        WM_DisableWindow(hAudioRecordButtonA);
        WM_DisableWindow(hAudioRecordButtonB);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateAudioRecordWindow(void) {
  if (!hAudioRecordWin) {
    hAudioRecordWin = GUI_CreateDialogBox(_aAudioRecordDialogCreate, GUI_COUNTOF(_aAudioRecordDialogCreate), _cbAudioRecordDialog, WM_HBKWIN, 0, 0);
  }
  return hAudioRecordWin;
}

// USER START (Optionally insert additional public code)

// USER END

/*************************** End of file ****************************/
