/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include <stdio.h>
#include "GUI_App.h"
#include "audioInputTools.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0  (GUI_ID_USER + 0x00)
#define ID_BUTTON_0  (GUI_ID_USER + 0x04)

// USER START (Optionally insert additional defines)

// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
WM_HWIN hFreqWave2Win =0;
int enableFreqWave2 = 0;
int rectDrawFinished = 1;
DefRectStruct rectangles[RECT_ARRAY_SIZE]= {0};
void initializeRectBuffer(){
  for (int i = 0; i < RECT_ARRAY_SIZE; i++){
     rectangles[i].x0 = 1;
     rectangles[i].y0 = 1;
     rectangles[i].x1 = 1;
     rectangles[i].y1 = 1;
  }
}

// USER END

/*********************************************************************
*
*       _aWaveDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aRecordWaveDialogCreate[] = {
  // 150 330
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Back", ID_BUTTON_0, 346, 213, 57, 44, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbWaveDialog
*/
static void _cbRecordqWaveDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    //
    // Initialization of 'Back'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_16_1);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Back'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
         Buzzer_Beep(240, 50);
         enableFreqWave2 = 0;
         enableFreqWaveDisplay = 0;
         AudioInputStop();
         WM_HideWindow(hFreqWave2Win);
         WM_DeleteWindow(hFreqWave2Win);
         hFreqWave2Win = 0;
         if (!hWin) hWin = CreateWindow();
         WM_ShowWindow(hWin);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  case WM_PAINT:

    for (int i=0;i<RECT_ARRAY_SIZE;i++){
      GUI_DrawGradientV(rectangles[i].x0,rectangles[i].y0, rectangles[i].x1, rectangles[i].y1, 0x0000FF, 0x00FFFF);
    }
    rectDrawFinished = 1;
    break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateFreqWave2Window(void) {
  if (!hFreqWave2Win) {
    hFreqWave2Win = GUI_CreateDialogBox(_aRecordWaveDialogCreate, GUI_COUNTOF(_aRecordWaveDialogCreate), _cbRecordqWaveDialog, WM_HBKWIN, 0, 0);
  }
  return hFreqWave2Win;
}

// USER START (Optionally insert additional public code)

// USER END

/*************************** End of file ****************************/
