/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include <stdio.h>
#include "GUI_App.h"
#include "audioInputTools.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0       (GUI_ID_USER + 0x00)
#define ID_TEXT_0       (GUI_ID_USER + 0x01)
#define ID_GRAPH_0       (GUI_ID_USER + 0x02)
#define ID_BUTTON_0       (GUI_ID_USER + 0x03)


// USER START (Optionally insert additional defines)

// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
WM_HWIN hWaveWin =0;
// 波形显示的数据区句柄
GRAPH_DATA_Handle hData= 0;
// 是否启用波形数据推流
int enableWaveDisplay = 0;

// USER END

/*********************************************************************
*
*       _aWaveDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aWaveDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 8, 5, 378, 33, 0, 0x64, 0 },
  { GRAPH_CreateIndirect, "Graph", ID_GRAPH_0, 13, 38, 362, 223, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Back", ID_BUTTON_0, 385, 211, 89, 46, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbWaveDialog
*/
static void _cbWaveDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetText(hItem, "Time-domain waveform display");
    TEXT_SetFont(hItem, GUI_FONT_32_1);
    //
    // Initialization of 'Back'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_16_1);
    // USER START (Optionally insert additional code for further widget initialization)
    /*
    *******************************************
    *****   这部分是配置波形显示器的代码  *****
    *******************************************
    */
    GRAPH_SCALE_Handle hScale;
    WM_HWIN hGraph;
    hGraph = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_0);
    hData  = GRAPH_DATA_YT_Create(GUI_RED, 400, NULL, 400);
    GRAPH_AttachData(hGraph, hData);
    hScale = GRAPH_SCALE_Create(28, GUI_TA_RIGHT, GRAPH_SCALE_CF_VERTICAL, 25); //刻度为25像素间隔
    GRAPH_AttachScale(hGraph, hScale);
    // 配置图形控件用于显示音频波形
    GRAPH_SetBorder(hGraph, 10, 10, 10, 10); //显示边框
    GRAPH_SetGridVis(hGraph, 1);  // 显示网格
    GRAPH_SetGridDistX(hGraph, 25); //网格间距
    GRAPH_SetGridDistY(hGraph, 25); //网格间距
    GRAPH_SetColor(hGraph, GUI_BLUE, GRAPH_CI_BK); //背景颜色
    GRAPH_SetColor(hGraph, GUI_LIGHTGRAY, GRAPH_CI_GRID); // 网格线颜色
    GRAPH_SCALE_SetOff(hScale,100); // 刻度偏移（正负）
    // GRAPH_SCALE_SetFactor(hScale, 1);  // 放缩因子
    
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Back'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
         Buzzer_Beep(240, 50);
         enableWaveDisplay = 0;
         AudioInputStop();
         WM_HideWindow(hWaveWin);
         WM_DeleteWindow(hWaveWin);
         hWaveWin = 0;
         if (!hWin) hWin = CreateWindow();
         WM_ShowWindow(hWin);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWaveWindow(void) {
  if (!hWaveWin) {
    hWaveWin = GUI_CreateDialogBox(_aWaveDialogCreate, GUI_COUNTOF(_aWaveDialogCreate), _cbWaveDialog, WM_HBKWIN, 0, 0);
  }
  return hWaveWin;
}

// USER START (Optionally insert additional public code)

// USER END

/*************************** End of file ****************************/
