/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include <stdio.h>
#include "GUI_App.h"
#include "audioInputTools.h"
#include "myclock.h"
#include "beep.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0    (GUI_ID_USER + 0x00)
#define ID_TEXT_0    (GUI_ID_USER + 0x01)
#define ID_BUTTON_0    (GUI_ID_USER + 0x02)
#define ID_TEXT_1    (GUI_ID_USER + 0x03)
#define ID_TEXT_2    (GUI_ID_USER + 0x04)
#define ID_TEXT_3    (GUI_ID_USER + 0x05)
#define ID_BUTTON_1    (GUI_ID_USER + 0x06)
#define ID_BUTTON_2    (GUI_ID_USER + 0x07)
#define ID_BUTTON_3    (GUI_ID_USER + 0x08)
#define ID_TEXT_4    (GUI_ID_USER + 0x09)
#define ID_TEXT_5    (GUI_ID_USER + 0x0A)
#define ID_TEXT_6    (GUI_ID_USER + 0x0B)
#define ID_BUTTON_4    (GUI_ID_USER + 0x0C)
#define ID_BUTTON_5    (GUI_ID_USER + 0x0D)
#define ID_BUTTON_6    (GUI_ID_USER + 0x0E)
#define ID_BUTTON_7    (GUI_ID_USER + 0x0F)
#define ID_BUTTON_8    (GUI_ID_USER + 0x10)
#define ID_BUTTON_9    (GUI_ID_USER + 0x11)
#define ID_BUTTON_10    (GUI_ID_USER + 0x12)
#define ID_TEXT_7     (GUI_ID_USER + 0x13)
#define ID_TEXT_8     (GUI_ID_USER + 0x14)
#define ID_BUTTON_11  (GUI_ID_USER + 0x15)
#define ID_BUTTON_12    (GUI_ID_USER + 0x16)
// USER START (Optionally insert additional defines)

// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
WM_HWIN hWin = 0;
WM_HWIN hTimeText =0;
WM_HWIN hAlarmText =0;
WM_HWIN hTimePointer = 0;
WM_HWIN hAlarmPointer = 0;
int isEditingTime= 0;
int isEditingAlarm = 0;
int isAlarmEnabled = 0;
WM_HWIN hMenu1= 0;
WM_HWIN hMenu2= 0;
WM_HWIN hMenu3= 0;
WM_HWIN hMenu4= 0;
WM_HWIN hMenu5= 0;
WM_HWIN hSetTimeBtn= 0;
WM_HWIN hSetAlarmBtn= 0;
WM_HWIN hAlarmSwitch = 0;
extern RTC_HandleTypeDef hrtc;
extern TIM_HandleTypeDef htim12;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Menu", ID_TEXT_0, 13, 9, 77, 33, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Wave Display", ID_BUTTON_0, 12, 61, 102, 28, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Developed by :", ID_TEXT_1, 371, 204, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "???", ID_TEXT_2, 339, 226, 127, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "???", ID_TEXT_3, 342, 244, 124, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Freq Display", ID_BUTTON_1, 12, 100, 102, 28, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Freq Display 2", ID_BUTTON_2, 12, 139, 102, 28, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Audio Record", ID_BUTTON_3, 12, 178, 102, 28, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Play Music", ID_BUTTON_12, 12, 217, 102, 28, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_4, 150, 38, 350, 68, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Alarm: ", ID_TEXT_5, 212, 80, 80, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "00:00:00", ID_TEXT_6, 291, 80, 80, 20, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "Set Alarm", ID_BUTTON_4, 332, 109, 75, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Set Time", ID_BUTTON_5, 206, 110, 75, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "+", ID_BUTTON_6, 173, 155, 35, 35, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "-", ID_BUTTON_7, 173, 222, 35, 35, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "<", ID_BUTTON_8, 140, 188, 35, 35, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, ">", ID_BUTTON_9, 205, 188, 35, 35, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Save", ID_BUTTON_10, 269, 157, 75, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_7, 150, 62, 350, 40, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_8, 291, 96, 80, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Off", ID_BUTTON_11, 380, 75, 25, 25, 0, 0x0, 0 },
  
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Menu'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
    //
    // Initialization of 'Wave Display'
    //
    hMenu1 = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hMenu1, GUI_FONT_16_1);
    //
    // Initialization of 'Developed by :'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'Freq Display'
    //
    hMenu2 = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hMenu2, GUI_FONT_16_1);
    //
    // Initialization of 'Freq Display 2'
    //
    hMenu3 = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hMenu3, GUI_FONT_16_1);
    //
    // Initialization of 'Audio Record'
    //
    hMenu4 = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetFont(hMenu4, GUI_FONT_16_1);
    //
    // Initialization of 'Play Music'
    //
    hMenu5 = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_12);
    BUTTON_SetFont(hMenu5, GUI_FONT_16_1);
    //
    // Initialization of '0000-00-00 00:00:00'
    //
    hTimeText = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hTimeText, GUI_FONT_32B_1);
    TEXT_SetTextColor(hTimeText, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Alarm:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetFont(hItem, GUI_FONT_20B_1);
    //
    // Initialization of '00:00:00'
    //
    hAlarmText = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetFont(hAlarmText, GUI_FONT_20B_1);
    //
    // Initialization of 'Set Alarm'
    //
    hSetAlarmBtn = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
    BUTTON_SetFont(hSetAlarmBtn, GUI_FONT_16_1);
    //
    // Initialization of 'Set Time'
    //
    hSetTimeBtn = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
    BUTTON_SetFont(hSetTimeBtn, GUI_FONT_16_1);
    //
    // Initialization of '+'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
    BUTTON_SetFont(hItem, GUI_FONT_20B_1);
    //
    // Initialization of '-'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
    BUTTON_SetFont(hItem, GUI_FONT_20B_1);
    //
    // Initialization of '<'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);
    BUTTON_SetFont(hItem, GUI_FONT_20B_1);
    //
    // Initialization of '>'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);
    BUTTON_SetFont(hItem, GUI_FONT_20B_1);
    //
    // Initialization of 'Save'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10);
    BUTTON_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of ''
    //
    hTimePointer = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetTextAlign(hTimePointer, GUI_TA_HCENTER | GUI_TA_TOP);
    TEXT_SetFont(hTimePointer, GUI_FONT_32B_1);
    TEXT_SetTextColor(hTimePointer, GUI_MAKE_COLOR(0x000000FF));
    //
    // Initialization of ''
    //
    hAlarmPointer = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetFont(hAlarmPointer, GUI_FONT_20B_1);
    TEXT_SetTextAlign(hAlarmPointer, GUI_TA_HCENTER | GUI_TA_TOP);
    TEXT_SetTextColor(hAlarmPointer, GUI_MAKE_COLOR(0x000000FF));
    //
    // Initialization of 'Off'
    //
    hAlarmSwitch = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11);
    BUTTON_SetFont(hAlarmSwitch, GUI_FONT_13B_1);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Wave Display'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
         Buzzer_Beep(240, 50,0);
         WM_HideWindow(hWin);
         if (!hWaveWin) hWaveWin = CreateWaveWindow();
         WM_ShowWindow(hWaveWin);
         enableWaveDisplay = 1;
           // ��ʼ����Ƶ����
         AudioInputInit();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Freq Display'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
         Buzzer_Beep(240, 50,0);
         WM_HideWindow(hWin);
         if (!hFreqWaveWin) hFreqWaveWin = CreateFreqWaveWindow();
         WM_ShowWindow(hFreqWaveWin);
         enableFreqWaveDisplay = 1;
         // ��ʼ����Ƶ����
         AudioInputInit();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    case ID_BUTTON_2: // Notifications sent by 'Wave Display 2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
         Buzzer_Beep(240, 50,0);
         WM_HideWindow(hWin);
         if (!hFreqWave2Win) hFreqWave2Win = CreateFreqWave2Window();
         WM_ShowWindow(hFreqWave2Win);
         enableFreqWaveDisplay = 1;
         enableFreqWave2 = 1;
         // ��ʼ����Ƶ����
         AudioInputInit();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    case ID_BUTTON_3: // Notifications sent by 'Audio Record'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
         Buzzer_Beep(240, 50,0);
         WM_HideWindow(hWin);
         if (!hAudioRecordWin) hAudioRecordWin = CreateAudioRecordWindow();
         WM_ShowWindow(hAudioRecordWin);
         enterAudioRecordPage = 1;
         // ��ʼ����Ƶ����
         AudioInputInit();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // �������Ӱ�ť
    case ID_BUTTON_4: // Notifications sent by 'Set Alarm'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // ���Ű�����Ч
        Buzzer_Beep(240, 50,0);
        isEditingAlarm = 1;
        // ���������������޹صİ�ť
        WM_DisableWindow(hMenu1);
        WM_DisableWindow(hMenu2);
        WM_DisableWindow(hMenu3);
        WM_DisableWindow(hMenu4);
        WM_DisableWindow(hMenu5);
        WM_DisableWindow(hSetTimeBtn);
        WM_DisableWindow(hSetAlarmBtn);
        // ��ȡ�޸�ǰ���ӵ����ֵ�����棬���ں������޸�
        RTC_AlarmTypeDef sAlarm;
        HAL_RTC_GetAlarm(&hrtc, &sAlarm, RTC_ALARM_A, RTC_FORMAT_BIN);
        alarmSecond = sAlarm.AlarmTime.Seconds;
        alarmMin = sAlarm.AlarmTime.Minutes;
        alarmHour = sAlarm.AlarmTime.Hours;
        // ��λ����ʾѡ��Ҫ��ĵ����ݵ�ָ��
        alarmPointCount = 0;
        RefreshSelectAlarmPointer();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // ����ʱ�䰴ť����ʱ��ͬ��
    case ID_BUTTON_5: // Notifications sent by 'Set Time'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        Buzzer_Beep(240, 50,0);
        isEditingTime = 1;
        WM_DisableWindow(hMenu1);
        WM_DisableWindow(hMenu2);
        WM_DisableWindow(hMenu3);
        WM_DisableWindow(hMenu4);
        WM_DisableWindow(hMenu5);
        WM_DisableWindow(hSetTimeBtn);
        WM_DisableWindow(hSetAlarmBtn);
        RTC_TimeTypeDef sTime;
        RTC_DateTypeDef sDate;
        HAL_RTC_GetTime(&hrtc, &sTime, RTC_FORMAT_BIN);
        HAL_RTC_GetDate(&hrtc, &sDate, RTC_FORMAT_BIN);
        timeSecond = sTime.Seconds;
        timeMin = sTime.Minutes;
        timeHour  = sTime.Hours;
        timeWeek  = sDate.WeekDay-1;
        timeDay  = sDate.Date;
        timeMon  = sDate.Month;
        timeYear  = sDate.Year;
        timePointCount = 0;
        RefreshSelectTimePointer();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by '+'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        Buzzer_Beep(240, 50,0);
        // ------------------------�����ǰ���ڱ༭����------------------------
        if(isEditingAlarm){
          // ����ָ��ѭ���Եĵ�������ֵ
          switch(alarmPointCount){
            case 0:
              alarmHour = (alarmHour + 1) % 24;
              break;
            case 1:
              alarmMin = (alarmMin + 1) % 60;
              break;
            case 2:
              alarmSecond = (alarmSecond + 1) % 60;
              break;
          }
          // ��ʾ���޸ĵ�δ���������
          DisplayTempAlarm();
        }
        // ------------------------�����ǰ���ڱ༭����ʱ��------------------------
        else if(isEditingTime){
          switch(timePointCount){
            // ��
            case 0:
              timeYear = (timeYear + 1) % 100;
              break;
            // ��
            case 1:
              timeMon ++;
              if(timeMon > 12) timeMon = 1;
              if(timeMon == 2 | timeMon == 4|timeMon ==6|timeMon ==9|timeMon ==11){
                if(timeMon == 4|timeMon ==6|timeMon ==9|timeMon ==11){
                  if(timeDay >30){
                    timeDay = 30;
                  }
                }
                else{
                  if(timeYear % 4 != 0){
                    if(timeDay >29){
                      timeDay = 29;
                    }
                  }
                  else{
                    if(timeDay >28){
                      timeDay = 28;
                    }
                  }
                }
              }
              break;
            // ��
            case 2:
              if(timeMon == 1|timeMon ==3|timeMon ==5|timeMon ==7|timeMon ==8|timeMon ==10|timeMon ==12){
                timeDay ++;
                if(timeDay>31) timeDay = 1;
              }
              else if(timeMon == 4|timeMon ==6|timeMon ==9|timeMon ==11){
                timeDay ++;
                if(timeDay>30) timeDay = 1;
              }
              else if(timeMon == 2){
                if(timeYear % 4 != 0){
                  timeDay ++;
                  if(timeDay>29) timeDay = 1;
                }
                else {
                  timeDay ++;
                  if(timeDay>28) timeDay = 1;
                }
              }
              break;
            // ����
            case 3:
              timeWeek = (timeWeek + 1) % 7;
              break;
            // ʱ
            case 4:
              timeHour = (timeHour + 1) % 24;
              break;
            // ��
            case 5:
              timeMin = (timeMin + 1) % 60;
              break;
            // ��
            case 6:
              timeSecond = (timeSecond + 1) % 60;
              break;
          }
          DisplayTempTime();
        }
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_7: // Notifications sent by '-'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        Buzzer_Beep(240, 50,0);
        if(isEditingAlarm){
          switch(alarmPointCount){
            case 0:
              alarmHour = (alarmHour + 23) % 24;
              break;
            case 1:
              alarmMin = (alarmMin + 59) % 60;
              break;
            case 2:
              alarmSecond = (alarmSecond + 59) % 60;
              break;
          }
          DisplayTempAlarm();
        }
        else if(isEditingTime){
          switch(timePointCount){
            case 0:
              timeYear = (timeYear + 99) % 100;
              break;
            case 1:
              timeMon--;
              if(timeMon < 1) timeMon = 12;
              if(timeMon == 2 | timeMon == 4|timeMon ==6|timeMon ==9|timeMon ==11){
                if(timeMon == 4|timeMon ==6|timeMon ==9|timeMon ==11){
                  if(timeDay >30){
                    timeDay = 30;
                  }
                }
                else{
                  if(timeYear % 4 != 0){
                    if(timeDay >29){
                      timeDay = 29;
                    }
                  }
                  else{
                    if(timeDay >28){
                      timeDay = 28;
                    }
                  }
                }
              }
              break;
            case 2:
              if(timeMon == 1|timeMon ==3|timeMon ==5|timeMon ==7|timeMon ==8|timeMon ==10|timeMon ==12){
                timeDay --;
                if(timeDay<1) timeDay = 31;
              }
              else if(timeMon == 4|timeMon ==6|timeMon ==9|timeMon ==11){
                timeDay --;
                if(timeDay<1) timeDay = 30;
              }
              else if(timeMon == 2){
                if(timeYear % 4 != 0){
                  timeDay --;
                  if(timeDay<1) timeDay = 29;
                }
                else {
                  timeDay --;
                  if(timeDay<1) timeDay = 28;
                }
              }
              break;
            case 3:
              timeWeek = (timeWeek + 6) % 7;
              break;
            case 4:
              timeHour = (timeHour + 23) % 24;
              break;
            case 5:
              timeMin = (timeMin + 59) % 60;
              break;
            case 6:
              timeSecond = (timeSecond + 59) % 60;
              break;
          }
          DisplayTempTime();
        }
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_8: // Notifications sent by '<'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        Buzzer_Beep(240, 50,0);
        // ����ָ�벢��ʾ
        if(isEditingAlarm){
          alarmPointCount = (alarmPointCount + 2) % 3;
          RefreshSelectAlarmPointer();
        }
        else if(isEditingTime){
          timePointCount = (timePointCount + 6) % 7;
          RefreshSelectTimePointer();
        }
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_9: // Notifications sent by '>'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        Buzzer_Beep(240, 50,0);
        if(isEditingAlarm){
          alarmPointCount = (alarmPointCount + 1) % 3;
          RefreshSelectAlarmPointer();
        }
        else if(isEditingTime){
          timePointCount = (timePointCount + 1) % 7;
          RefreshSelectTimePointer();
        }
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // ���水ť
    case ID_BUTTON_10: // Notifications sent by 'Save'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        Buzzer_Beep(240, 50,0);
        // ʹ�ܰ�ť�����޸ĺ��ֵ����
        if(isEditingAlarm){
          isEditingAlarm = 0;
          TEXT_SetText(hAlarmPointer,"");
          WM_EnableWindow(hMenu1);
          WM_EnableWindow(hMenu2);
          WM_EnableWindow(hMenu3);
          WM_EnableWindow(hMenu4);
          WM_EnableWindow(hMenu5);
          WM_EnableWindow(hSetTimeBtn);
          WM_EnableWindow(hSetAlarmBtn);
          SaveAlarm();
        }
        else if(isEditingTime){
          isEditingTime = 0;
          TEXT_SetText(hTimePointer,"");
          WM_EnableWindow(hMenu1);
          WM_EnableWindow(hMenu2);
          WM_EnableWindow(hMenu3);
          WM_EnableWindow(hMenu4);
          WM_EnableWindow(hMenu5);
          WM_EnableWindow(hSetTimeBtn);
          WM_EnableWindow(hSetAlarmBtn);
          SaveTime();
        }
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_11: // Notifications sent by 'Off'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        Buzzer_Beep(240, 50,0);
        if(isAlarmEnabled) {
          isAlarmEnabled = 0;
          BUTTON_SetText(hAlarmSwitch, "Off");
          // �ı�����������ɫ
          TEXT_SetTextColor(hAlarmText, GUI_MAKE_COLOR(0x00000000));
          // ʹ�������ж�
          HAL_NVIC_DisableIRQ(RTC_Alarm_IRQn);
        }
        else {
          isAlarmEnabled = 1;
          BUTTON_SetText(hAlarmSwitch, "On");
          TEXT_SetTextColor(hAlarmText, GUI_MAKE_COLOR(0x00008000));
          HAL_NVIC_EnableIRQ(RTC_Alarm_IRQn);
        }
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_12: // Notifications sent by 'Play Music'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        Buzzer_Beep(240, 50,0);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) {
  if (!hWin) {
    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  }
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
